## Learn Numpy

Numpy stands for numberical python. It is one of the most useful scientific libraries available in python. 

In [2]:
import numpy as np

# Creating basic arrays

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
np.array([1,2,3,4,5], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)


# Creating multi dimentional arrays

In [9]:
np.array([[1,2,3,4,5],
         [6,7,8,9,10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Array creation utilities

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(5, dtype=np.int32)

array([1, 1, 1, 1, 1])

In [18]:
np.ones((2,5), dtype=np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.full(5, 6)

array([6, 6, 6, 6, 6])

In [21]:
np.full((2,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# Identity matrix 
Identity matrix will have nxn shape (same number of rows and columns)

In [23]:
np.eye(5, dtype=np.int32)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

but numpy gives a flexibility to change the diagonal along which values have to be 1 

Below are such examples, but these matrices are not identity matrices

In [24]:
np.eye(5, k=1, dtype=np.int32)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [25]:
np.eye(5, k=2, dtype=np.int32)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.eye(5, k=-2, dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

# Random numbers

In [29]:
np.random.rand(2)

array([0.48883876, 0.50641414])

In [34]:
# np.random.rand((2, 5)) won't work
np.random.rand(2,5)

array([[0.92925929, 0.02721113, 0.72287809, 0.46048951, 0.40972392],
       [0.16829413, 0.80430275, 0.70873261, 0.42095826, 0.92607743]])

In [35]:
np.random.rand(3,3,3)

array([[[0.7205646 , 0.3330267 , 0.17468122],
        [0.70581456, 0.35053143, 0.02476868],
        [0.53383295, 0.70111349, 0.97354785]],

       [[0.51844479, 0.04308936, 0.56106173],
        [0.12940232, 0.60742056, 0.32048215],
        [0.27877408, 0.0805756 , 0.15198529]],

       [[0.85430327, 0.00853194, 0.04149457],
        [0.77405264, 0.37530807, 0.60740123],
        [0.95835878, 0.77596865, 0.33246187]]])

# Utility functions

# arange

Evenly spaced n-dimensional array <br>

np.arange(start, end, step)

In [36]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [39]:
np.arange(5, 20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
np.arange(5, 20, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

# linspace

Similar to arange, but instead of step it acccepts size <br>

np.linspace(start, end, size)


In [46]:
# default size is 50, 
# so if size is not specified linspace splits start and end with 50 even steps

np.linspace(5, 10)


array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [48]:
np.linspace(5, 10, 10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [55]:
# retstep gives the difference between points also along with output given by linspace

np.linspace(5, 10, 10, retstep=True)

(array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
         7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ]),
 0.5555555555555556)

# Dimensions and Shapes

In [77]:
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [78]:
arr1.ndim

1

In [79]:
arr2 = np.zeros((1,5))
arr2

array([[0., 0., 0., 0., 0.]])

In [80]:
arr2.ndim

2

In [82]:
arr3 = np.array([np.zeros((1,5)), np.ones((1,5))], dtype=np.int32)
arr3

array([[[0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1]]])

In [83]:
arr3.ndim

3

In [84]:
arr.shape

(5,)

In [85]:
arr2.shape

(1, 5)

In [86]:
arr3.shape

(2, 1, 5)

In [87]:
arr1.size

5

In [88]:
arr2.size

5

In [89]:
arr3.size

10

# Reshaping

In [95]:
arr = np.arange(1,26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [96]:
arr.shape

(25,)

In [99]:
arr = arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [101]:
arr.shape

(5, 5)

In [106]:
arr.flatten() # returns copy of arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [111]:
arr.ravel() # returns original array, so any change on this return obj will affect actual array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

# array manipulation

Transpose

In [115]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [116]:
np.transpose(arr)

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

# Dimention addition and deletion

# Expanding dimension

In [126]:
arr = np.ones(5, dtype=np.int32)

In [127]:
# expanding after adding a column
new_arr = np.expand_dims(arr, axis=0)
new_arr

array([[1, 1, 1, 1, 1]])

In [128]:
new_arr.shape

(1, 5)

In [129]:
new_arr = np.expand_dims(arr, axis=1)
new_arr

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [130]:
new_arr.shape

(5, 1)

# Squeezing dimensions

In [144]:
arr = np.array([[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]]])

In [146]:
arr.shape

(1, 2, 3)

In [147]:
new_arr = np.squeeze(arr, axis=0)
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
new_arr.shape

(2, 3)

# Indexing and Slicing

# 1 dimension

In [152]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [153]:
arr[1]

2

In [154]:
arr[1:4]

array([2, 3, 4])

In [155]:
arr[1:4:2]

array([2, 4])

In [156]:
arr[::-1]

array([5, 4, 3, 2, 1])

# 2 dimension

In [158]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [159]:
arr.shape

(2, 5)

In [163]:
arr[0,2]

3

In [162]:
arr[1,3]

9

In [166]:
arr[0:3, 0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [172]:
arr[0:, 3:]

array([[ 4,  5],
       [ 9, 10]])

In [173]:
arr[0:, 0::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

# Stacking and Concatenation

In [190]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [191]:
# vertical stacking (or) row addition
np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [192]:
# horizontal stacking (or) column addition
np.hstack((arr1, arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [195]:
arr1 = np.arange(0, 5).reshape(1,5)
arr2 = np.arange(5, 10).reshape(1,5)
arr1, arr2

(array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]))

In [196]:
np.concatenate((arr1, arr2), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [197]:
np.concatenate((arr1, arr2), axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [198]:
np.append(arr1, arr2, axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [199]:
np.append(arr1, arr2, axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])