## Learn Numpy

Numpy stands for numberical python. It is one of the most useful scientific libraries available in python. 

In [229]:
import numpy as np

# Creating basic arrays

In [230]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [231]:
np.array([1,2,3,4,5], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)


# Creating multi dimentional arrays

In [232]:
np.array([[1,2,3,4,5],
         [6,7,8,9,10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Array creation utilities

In [233]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [234]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [235]:
np.ones(5, dtype=np.int32)

array([1, 1, 1, 1, 1])

In [236]:
np.ones((2,5), dtype=np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [237]:
np.full(5, 6)

array([6, 6, 6, 6, 6])

In [238]:
np.full((2,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [239]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# Identity matrix 
Identity matrix will have nxn shape (same number of rows and columns)

In [240]:
np.eye(5, dtype=np.int32)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

but numpy gives a flexibility to change the diagonal along which values have to be 1 

Below are such examples, but these matrices are not identity matrices

In [241]:
np.eye(5, k=1, dtype=np.int32)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [242]:
np.eye(5, k=2, dtype=np.int32)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [243]:
np.eye(5, k=-2, dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

# Random numbers

In [244]:
np.random.rand(2)

array([0.64019082, 0.260191  ])

In [245]:
# np.random.rand((2, 5)) won't work
np.random.rand(2,5)

array([[0.0552572 , 0.5614072 , 0.62039786, 0.13821612, 0.62075553],
       [0.56225305, 0.21922285, 0.28198331, 0.45512499, 0.73532764]])

In [246]:
np.random.rand(3,3,3)

array([[[0.52032604, 0.3216644 , 0.53723532],
        [0.75199857, 0.57010606, 0.74485836],
        [0.42226973, 0.4016839 , 0.81049605]],

       [[0.33958426, 0.94493003, 0.90297738],
        [0.10230194, 0.26383868, 0.80048929],
        [0.02398382, 0.90620087, 0.24594563]],

       [[0.62226013, 0.7479126 , 0.56959781],
        [0.98439179, 0.03113458, 0.83653068],
        [0.77299114, 0.3462665 , 0.84306778]]])

In [247]:
np.random.randint(5, 10, size=(4,4), dtype=np.int32)

array([[9, 5, 8, 7],
       [7, 6, 7, 8],
       [6, 6, 5, 7],
       [7, 8, 6, 6]])

# Utility functions

# arange

Evenly spaced n-dimensional array <br>

np.arange(start, end, step)

In [248]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [249]:
np.arange(5, 20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [250]:
np.arange(5, 20, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

# linspace

Similar to arange, but instead of step it acccepts size <br>

np.linspace(start, end, size)


In [251]:
# default size is 50, 
# so if size is not specified linspace splits start and end with 50 even steps

np.linspace(5, 10)


array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [252]:
np.linspace(5, 10, 10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [253]:
# retstep gives the difference between points also along with output given by linspace

np.linspace(5, 10, 10, retstep=True)

(array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
         7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ]),
 0.5555555555555556)

# Dimensions and Shapes

In [254]:
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [255]:
arr1.ndim

1

In [256]:
arr2 = np.zeros((1,5))
arr2

array([[0., 0., 0., 0., 0.]])

In [257]:
arr2.ndim

2

In [258]:
arr3 = np.array([np.zeros((1,5)), np.ones((1,5))], dtype=np.int32)
arr3

array([[[0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1]]])

In [259]:
arr3.ndim

3

In [260]:
arr3.shape

(2, 1, 5)

In [261]:
arr2.shape

(1, 5)

In [262]:
arr3.shape

(2, 1, 5)

In [263]:
arr1.size

5

In [264]:
arr2.size

5

In [265]:
arr3.size

10

# Reshaping

In [266]:
arr = np.arange(1,26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [267]:
arr.shape

(25,)

In [268]:
arr = arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [269]:
arr.shape

(5, 5)

In [270]:
arr.flatten() # returns copy of arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [271]:
arr.ravel() # returns original array, so any change on this return obj will affect actual array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

# Flip and Transpose

In [272]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [273]:
np.transpose(arr)

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [274]:
np.flip(arr)

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

# Dimention addition and deletion

# Expanding dimension

In [275]:
arr = np.ones(5, dtype=np.int32)

In [276]:
# expanding after adding a column
new_arr = np.expand_dims(arr, axis=0)
new_arr

array([[1, 1, 1, 1, 1]])

In [277]:
new_arr.shape

(1, 5)

In [278]:
new_arr = np.expand_dims(arr, axis=1)
new_arr

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [279]:
new_arr.shape

(5, 1)

# Squeezing dimensions

In [280]:
arr = np.array([[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]]])

In [281]:
arr.shape

(1, 2, 3)

In [282]:
new_arr = np.squeeze(arr, axis=0)
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [283]:
new_arr.shape

(2, 3)

# Indexing and Slicing

# 1 dimension

In [284]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [285]:
arr[1]

2

In [286]:
arr[1:4]

array([2, 3, 4])

In [287]:
arr[1:4:2]

array([2, 4])

In [288]:
arr[::-1]

array([5, 4, 3, 2, 1])

# 2 dimension

In [289]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [290]:
arr.shape

(2, 5)

In [291]:
arr[0,2]

3

In [292]:
arr[1,3]

9

In [293]:
arr[0:3, 0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [294]:
arr[0:, 3:]

array([[ 4,  5],
       [ 9, 10]])

In [295]:
arr[0:, 0::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

# Stacking and Concatenation

In [296]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [297]:
# vertical stacking (or) row addition
np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [298]:
# horizontal stacking (or) column addition
np.hstack((arr1, arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [299]:
arr1 = np.arange(0, 5).reshape(1,5)
arr2 = np.arange(5, 10).reshape(1,5)
arr1, arr2

(array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]))

In [300]:
np.concatenate((arr1, arr2), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [301]:
np.concatenate((arr1, arr2), axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [302]:
np.append(arr1, arr2, axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [303]:
np.append(arr1, arr2, axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Hsplit and Vsplit

In [304]:
arr = np.random.randint(5, size=(4,4), dtype=np.int32)
arr

array([[2, 2, 0, 2],
       [3, 0, 4, 4],
       [0, 4, 4, 1],
       [0, 2, 4, 4]])

In [305]:
np.hsplit(arr,2)

[array([[2, 2],
        [3, 0],
        [0, 4],
        [0, 2]]),
 array([[0, 2],
        [4, 4],
        [4, 1],
        [4, 4]])]

In [306]:
np.hsplit(arr, 4)

[array([[2],
        [3],
        [0],
        [0]]),
 array([[2],
        [0],
        [4],
        [2]]),
 array([[0],
        [4],
        [4],
        [4]]),
 array([[2],
        [4],
        [1],
        [4]])]

In [307]:
np.vsplit(arr, 2)

[array([[2, 2, 0, 2],
        [3, 0, 4, 4]]),
 array([[0, 4, 4, 1],
        [0, 2, 4, 4]])]

# other functions

# unique

In [308]:
arr = np.array([1,1,2,2,2,3,4,5,5])
arr

array([1, 1, 2, 2, 2, 3, 4, 5, 5])

In [309]:
np.unique(arr)

array([1, 2, 3, 4, 5])

# aggregate functions

In [310]:
arr

array([1, 1, 2, 2, 2, 3, 4, 5, 5])

In [311]:
np.sum(arr)

25

In [312]:
np.cumsum(arr, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.cumsum(arr, axis=0)

# argmax and argmin

In [ ]:
arr = np.array([[5,4,3,2,1],
               [6,7,8,9,10]])
arr

In [ ]:
# returns index of maximum element of array
np.argmax(arr)

In [ ]:
# column wise
np.argmax(arr, axis=0)

In [ ]:
# row wise
np.argmax(arr, axis=1)

In [ ]:
# returns index of minimum element of array
np.argmin(arr)

In [ ]:
np.argmin(arr, axis=0)

In [ ]:
np.argmin(arr, axis=1)

# shuffle

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

In [ ]:
np.random.shuffle(arr)
arr

# count non zero

In [ ]:
np.count_nonzero(arr)

# absolute

In [ ]:
arr = np.random.randint(-5, 5 , size=(4,4), dtype=np.int32)
arr

In [ ]:
np.abs(arr)

# sorting

In [ ]:
arr

In [ ]:
np.sort(arr, axis=0)

In [ ]:
np.sort(arr, axis=1)

In [ ]:
np.sort(arr, kind='mergesort', axis=1)

In [ ]:
arr